Fix @Default method brigadier tab completion
aikar/commands pull request #357
Opened 2022-01-10 00:02 UTC by DeathRealms

Fixes tab completion for the default method when brigadier api is enabled (#330)

2022-01-10 00:05 UTC, JOO200 commented
Maybe extract the duplicated code in a new method?

2022-01-10 13:53 UTC, JOO200 requested changes

2022-01-10 13:53 UTC, JOO200 commented on brigadier/src/main/java/co.aikar.commands/ACFBrigadierManager.java
> +            registerParameters(parameters, rootCommand, paramNode, suggestionProvider, executor, permCheckerRoot);
Why do you pass the rootCommand and permCheckerRoot here? pretty sure it's enough to pass `rootCommand.getDefaultRegisteredCommand()` and `permCheckerSub`.

Your current implementation will provide wrong suggestions for @Default command methods with a @CommandPermission.

2022-01-10 13:53 UTC, JOO200 commented on brigadier/src/main/java/co.aikar.commands/ACFBrigadierManager.java
> +    <C> void registerParameters(CommandParameter[] parameters,
Doesn't need to be a generic method when you're only using RegisteredCommand and the permCheckerSub

2022-01-12 02:07 UTC, DeathRealms commented
I still need to figure out why when registering the parameters for the default method it prevents sub commands you don't have permission for from being removed from tab completion, but they get removed if you don't have permission for both the default and sub command.

2022-01-31 12:07 UTC, merged

2022-01-31 12:10 UTC, chickeneer commented
This change looks reasonable. In regards to the latter comment about 

> when registering the parameters for the default method it prevents sub commands you don't have permission for from being removed from tab completion, but they get removed if you don't have permission for both the default and sub command.

I think it clear you are making this comment in general and shouldn't block merging this.